### ISSUE TITLE
ImportError: cannot import name 'assoc_mac_to_ip' from 'mreg_cli.dhcp' 

### ISSUE THREAD

**Issue by terjekv** [unioslo/mreg-cli#114]
mreg-cli fails to find `assoc_mac_to_ip` in https://github.com/unioslo/mreg-cli/blob/master/mreg_cli/dhcp.py:
```
➜  mreg-cli master ✓$ mreg-cli
Connecting to https://mreg.uio.no
Password for terjekv-drift:
Traceback (most recent call last):
  File "/usr/local/bin/mreg-cli", line 11, in <module>
    load_entry_point('mreg-cli==0.0.0', 'console_scripts', 'mreg-cli')()
  File "/usr/local/lib/python3.7/site-packages/mreg_cli-0.0.0-py3.7.egg/mreg_cli/main.py", line 113, in main
    from . import host      # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/mreg_cli-0.0.0-py3.7.egg/mreg_cli/host.py", line 5, in <module>
    from .dhcp import assoc_mac_to_ip
ImportError: cannot import name 'assoc_mac_to_ip' from 'mreg_cli.dhcp' (/usr/local/lib/python3.7/site-packages/mreg_cli-0.0.0-py3.7.egg/mreg_cli/dhcp.py)
➜  mreg-cli master ✓$ grep assoc_mac_to_ip -r mreg_cli/*
mreg_cli/host.py:from .dhcp import assoc_mac_to_ip
mreg_cli/host.py:            assoc_mac_to_ip(args.macaddress, ipdata, force=args.force)
mreg_cli/host.py:            assoc_mac_to_ip(macaddress, ip, force=args.force)
```

**Comment by oyvindkolbu** [comment]
Forgot to commit `dhcp.py` in d6efcb1e76fae917ac0b89e61b693c04922095e7. Resolved now.
